on:
  workflow_dispatch:
  check_run:
    types: [rerequested]
  schedule:
    - cron: '17 4 * * *'

jobs:
  epic5:
    runs-on: ubuntu-latest
    steps:
    - name: install ssh key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: mirror epic5 repo
      run: |
        git clone --mirror http://git.epicsol.org/epic5.git/
        cd epic5.git
        git push --mirror git@github.com:ailin-nemui/epic5.git
    - name: uninstall ssh key
      run: |
        rm -fr ~/.ssh
  stamp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: commit changes
      run: |
        date +'%G%V' > .wk
        git config user.email "cron@ailin-nemui.github.io"
        git config user.name "GitHub Cronjobs"
        git add .wk
        git commit -m "Run from $(date)" || :
        git push
